WebAudioConf/webaudioconf.github.io

src/components/twitter.js
src/pages/call-for-submissions.js
src/pages/index.js

It's been recommended for a long time due to: https://mathiasbynens.github.io/rel-noopener

Make sure to pass rel="noopener" for external links

---

src/pages/call-for-submissions.js

Apply 'final' cfs changes

---

src/pages/index.css
src/pages/index.js

Announce the speakers page on the index page

---

README.md
gatsby-config.js

realised the generated sitemap.xml contained absolute links with `http://`

http:// => https://

---

src/components/person.js
src/helpers/break-parts.js

committee page: line break on slashes

---

src/components/announcement.css
src/layouts/index.js
src/pages/index.css
src/pages/index.js

Add ticket link + button

---

src/pages/program.js

This pull request just updates an installation title. I guess it's fine to merge it right away.

update installation title

---

src/pages/schedule.js

See title ;)
Will merge as this is a small change.

Add link to audiogustatory and spell BRLO correctly

---

src/pages/program.js

This pull request just removes a canceled talk.

remove talk from Eduardo Shiota Yasuda

---

src/pages/program.js

as unfortunately Eliza can't make it anymore

remove "Seeing Sound - How Do You Listen" installation

---

src/pages/program.js

because unfortunately they can't make it anymore

remove web audio and paper interfaces installation

---

src/pages/program.js

Unfortunately, Karim will not be able to attend this year.

Remove demo from Karim Ratib

---

src/pages/schedule.js

Update times and description for dinner and concert to reflect the current planning

Update times and description for dinner and concert

---

src/pages/committee.js

As discussed in the sync today, I added the program committee

Add the program committee

---

src/pages/schedule.css
src/pages/schedule.js

I think separating the title and the authors makes for an easier-to-read schedule, what do you think?
|Before | After|
|--------|-------|
| ![screen shot 2018-09-16 at 18 49 01](https://user-images.githubusercontent.com/68591/45598748-3901ce80-b9e1-11e8-98e0-69046559b4e3.jpg) | ![screen shot 2018-09-16 at 18 46 46](https://user-images.githubusercontent.com/68591/45598756-3b642880-b9e1-11e8-80f7-96618b1654ab.jpg) |

Separate title and authors

---

src/data/accepted-submissions.json

Change performance order to reflect actual order at the concert

---

src/data/accepted-submissions.json

Fix author name of audio pipes

---

src/pages/schedule.js

This pull requests adds the workshops to the schedule.

add workshops to schedule

---

src/data/accepted-submissions.json
src/pages/schedule.js

This pull request removes the talk from Naomi Aro.

remove talk from Naomi Aro

---

src/pages/index.js
src/pages/info.css

This is embedding the live stream. :-)

embed video stream

---

src/pages/schedule.css
src/pages/schedule.js

Adds a button that links to the current slot

---

src/data/accepted-submissions.json

This pull request moves around the performance "No merge conflicts" to be scheduled as the third performance.

reschedule 'No merge conflicts'

---

src/data/accepted-submissions.json

This pull request flips the order of the performances by Charles Roberts and Jasmine Guffond.

reorder performances

---

src/pages/schedule.js

this installation is happening today now because Tate also had a slot with posters at the same time yesterday

move "a more perfect union" installation to today

---

src/pages/committee.js

This updates the live stream link for tomorrow.
DON'T MERGE IT YET. :-)

update live stream link for day two

---

src/pages/committee.js
src/pages/index.js

Fix day 2 livestream

---

src/pages/schedule.js

This pull request adds the missing paper for the poster "WebAudio Virtual Tube Guitar Amps and Pedal Board Design" to the schedule.

add paper for poster
